### ISSUE TITLE
Lighthouse doesnt work after window resize

### ISSUE THREAD

**Issue by Felioh** [b3z/projectLighthouse#15]

**Comment by b3z** [comment]
@Felioh Nur bei windows?

**Comment by Felioh** [comment]
> @Felioh Nur bei windows?

Teste mal bitte

**Comment by b3z** [comment]
@Felioh Lighthouse geht bei mir generell nie 😂

**Comment by b3z** [comment]
We could fix that by just not resizing the window... @Felioh
